# Generated by Django 6.0.2 on 2026-02-28 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='status',
        ),
        migrations.CreateModel(
            name='DailyTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailytask')),
            ],
            options={
                'unique_together': {('task', 'date')},
            },
        ),
    ]
